%tr = (%tr,
'advproxylog proxy log' => 'Advanced Proxy Logs',
'advproxylog options' => 'Opzioni Advanced Proxy Log',
'advproxylog response code' => 'Codice Risposta',
'advproxylog enable match criteria' => 'Abilita Criteri Corrispondenza',
'advproxylog match criteria' => 'Criteri Corrispondenza',
'advproxylog sort by' => 'Ordina per',
'advproxylog sort by date' => 'Data',
'advproxylog sort by result code' => 'Codice Risposta',
'advproxylog sort by duration' => 'Durata',
'advproxylog sort by duration and size' => 'Durata e Grandezza',
'advproxylog sort by size' => 'Grandezza',
'advproxylog sort by url' => 'URL',
'advproxylog order asc' => 'ASC',
'advproxylog order desc' => 'DISC',
'advproxylog order' => 'Ordine',
'advproxylog truncate url' => 'Tronca Url',
'advproxylog full url' => 'Url Completo',
'advproxylog measures raw' => 'Non formattare le colonne Grandezza, Velocità e Durata',
'advproxylog duration in sec' => 'Durata (in sec)',
'advproxylog duration in ms' => 'Durata (in ms)',
'advproxylog duration' => 'Durata',
'advproxylog size in hr' => 'Grandezza',
'advproxylog size in bytes' => 'Grandezza (in bytes)',
'advproxylog transfer rate speed' => 'Velocità Trasferimento',
'advproxylog sorting options' => 'Opzioni Ordinamento',
'advproxylog request method' => 'Metodo Richiesta',
'advproxylog update notification' => 'AdvProxyLog - Aggiornamenti Disponibili!',
'advproxylog update information' => 'Disponibile un nuovo aggiornamento per AdvProxyLog. Visita <a href="http://joeyramone76.altervista.org/advproxylog" target="_blank">http://joeyramone76.altervista.org/advproxylog</a> per informazioni e download.',
'advproxylog current installed version' => 'Versione attualmente installata',
'advproxylog prev' => 'Precedente',
'advproxylog next' => 'Successiva',
);

