%tr = (%tr,
'advproxylog proxy log' => 'Advanced Proxy Logs',
'advproxylog options' => 'AdvProxyLog Options',
'advproxylog response code' => 'Response Code',
'advproxylog enable match criteria' => 'Enable Match Criteria',
'advproxylog match criteria' => 'Match Criteria',
'advproxylog sort by' => 'Sort by',
'advproxylog sort by date' => 'Date',
'advproxylog sort by result code' => 'Response code',
'advproxylog sort by duration' => 'Duration',
'advproxylog sort by duration and size' => 'Duration and Size',
'advproxylog sort by size' => 'Size',
'advproxylog sort by url' => 'URL',
'advproxylog order asc' => 'ASC',
'advproxylog order desc' => 'DESC',
'advproxylog order' => 'Order',
'advproxylog truncate url' => 'Truncate Url',
'advproxylog full url' => 'Full Url',
'advproxylog measures raw' => 'No Format for Size, Speed and Duration column',
'advproxylog duration in sec' => 'Duration (in sec)',
'advproxylog duration in ms' => 'Duration (in ms)',
'advproxylog duration' => 'Duration',
'advproxylog size in hr' => 'Size',
'advproxylog size in bytes' => 'Size (in bytes)',
'advproxylog transfer rate speed' => 'Transfer Rate',
'advproxylog sorting options' => 'Sorting Options',
'advproxylog request method' => 'Request Method',
'advproxylog update notification' => 'Update notification!',
'advproxylog update information' => 'There is an updated version available for download. Visit <a href="http://joeyramone76.altervista.org/advproxylog" target="_blank">http://joeyramone76.altervista.org/advproxylog</a> for more information.',
'advproxylog current installed version' => 'Current Installed Version',
);

